### ISSUE TITLE
求助 T_T，找不到supervision导致Improt失败

### ISSUE THREAD

**Issue by K-O-N-B** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#18]
Traceback (most recent call last):
  File "H:\ComfyUI-qiuye\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\__init__.py", line 1, in <module>
    from . import YOLO_WORLD_EfficientSAM
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 6, in <module>
    import supervision as sv
ModuleNotFoundError: No module named 'supervision'

Cannot import H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM module for custom nodes: No module named 'supervision'

小白如何解决这个问题，求回答

**Comment by lordwedggie** [comment]
Same problem here

**Comment by pospisk** [comment]
@K-O-N-B & @lordwedggie 

`pip install supervision`

**Comment by K-O-N-B** [comment]
> @K-O-N-B & @lordwedggie
> 
> `pip install supervision`

thank you
