### ISSUE TITLE
yoloworld AttributeError: type object 'Detections' has no attribute 'from_inference'

### ISSUE THREAD

**Issue by cyandddd** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#28]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\moloc\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\moloc\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\moloc\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\moloc\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 141, in yoloworld_esam_image
    detections = sv.Detections.from_inference(results)
AttributeError: type object 'Detections' has no attribute 'from_inference'

first time running and i encountered this. some package issus? how should i fix the code?

**Comment by cyandddd** [comment]
不知道这是出了什么问题 detections是不是最近更新然后from_inference改名了？我google都没有找到from_inference改名成啥了。请帮助，谢谢

**Comment by marsmana** [comment]
same error

**Comment by marsmana** [comment]
解决方案：pip supervision到0.21.0及以上
