### ISSUE TITLE
安装后在comfyUI中仍提示节点缺失

### ISSUE THREAD

**Issue by cndxflwb** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#37]
环境：Python 3.10.9 Windows 11 23H2 22631.3447

**When loading the graph, the following node types were not found:
ESAM_ModelLoader_Zho
Yoloworld_ESAM_Zho
Yoloworld_ModelLoader_Zho**

查看启动器的log，有：
Torch version: 2.0.1+cu118
Traceback (most recent call last):
  File "D:\ComfyUI_Full\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\__init__.py", line 1, in <module>
    from . import YOLO_WORLD_EfficientSAM
  File "D:\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 6, in <module>
    import supervision as sv
ModuleNotFoundError: No module named 'supervision'

Cannot import D:\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM module for custom nodes: No module named 'supervision'

'supervision' 模块，我使用pip list查看已经安装上了：
supervision                       0.19.0

文件目录：
D:.
│  .gitignore
│  efficient_sam_s_cpu.jit
│  efficient_sam_s_gpu.jit
│  LICENSE
│  README.md
│  requirements.txt
│  YOLO_WORLD_EfficientSAM.py
│  YOLO_WORLD_SEGS.py
│  __init__.py
│
├─utils
│      efficient_sam.py
│      video.py
│      __init__.py
│
├─YOLO_World_EfficientSAM_WORKFLOWS
│      YoloWorld-EfficientSAM V1.0 IMG 【Zho】.json
│      YoloWorld-EfficientSAM V1.0 VIDEO 【Zho】.json
│      YoloWorld-EfficientSAM V2.0 IMG 【Zho】.json
│      YoloWorld-EfficientSAM V2.0 VIDEO 【Zho】.json
│
└─__pycache__
        YOLO_WORLD_EfficientSAM.cpython-310.pyc
        __init__.cpython-310.pyc

**Comment by m-ali-awan** [comment]
for me installing `inference-gpu` solved the issue. As it was not installed. And I had to stop ComfyUI process, as it was not able to install with process running
