### ISSUE TITLE
我无法实现案例中的“蒙版分离”效果

### ISSUE THREAD

**Issue by Un1ess** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#55]
期望效果（案例）
![image_45](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/assets/70703095/b4147214-468c-4a3e-a516-fc517727f69d)

我的节点设置：
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/assets/70703095/a9e9e3af-cc95-4fe2-be5f-eb99544560a6)

运行后的报错信息：
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/assets/70703095/4a678f7c-f103-4d0c-84ea-cd8f2b608fa9)

报错信息具体：
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_Build\python_embeded\Lib\site-packages\PIL\Image.py", line 3098, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: ((1, 1, 12), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI_Build\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Build\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Build\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Build\ComfyUI\nodes.py", line 1439, in save_images
    img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Build\python_embeded\Lib\site-packages\PIL\Image.py", line 3102, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 12), |u1

**Comment by Un1ess** [comment]
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/assets/70703095/7817e334-c77a-43f5-8910-2781942059d6)
问题解决了，要先使用Mask List to Mask节点，然后再使用Convert Masks to Images
