### ISSUE TITLE
ImportError: cannot import name 'YOLOWorld' from 'inference.models' 

### ISSUE THREAD

**Issue by g-wellsa** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#63]
Traceback (most recent call last):
  File "G:\workspace\python\ComfyUI_nvidia_cu121_or_cpu\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\workspace\python\ComfyUI_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\__init__.py", line 1, in <module>
    from . import YOLO_WORLD_EfficientSAM
  File "G:\workspace\python\ComfyUI_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 9, in <module>
    from inference.models import YOLOWorld
ImportError: cannot import name 'YOLOWorld' from 'inference.models' (G:\workspace\python\ComfyUI_nvidia_cu121_or_cpu\python_embeded\Lib\site-packages\inference\models\__init__.py)

Cannot import G:\workspace\python\ComfyUI_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM module for custom nodes: cannot import name 'YOLOWorld' from 'inference.models' (G:\workspace\python\ComfyUI_nvidia_cu121_or_cpu\python_embeded\Lib\site-packages\inference\models\__init__.py)

**Comment by g-wellsa** [comment]
有人遇到这种问题吗，求解

**Comment by Un1ess** [comment]
遇到问题+1

**Comment by Cokeheart** [comment]
I have the same problem. Is there a way to solve it?

**Comment by g-wellsa** [comment]
No~~~


isa988
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月29日(星期六) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM] ImportError: cannot import name 'YOLOWorld' from 'inference.models'  (Issue #63)





 
I have the same problem. Is there a way to solve it?

**Comment by AntAreS24** [comment]
I found a way to get this up and running on MacOS M3.

1. Check if onnxruntime-gpu is installed. If yes, remove it:
```
cd custom_nodes/ComfyUI-YoloWorld-EfficientSAM
pip3 list | grep onnxruntime-gpu
pip3 uninstall onnxruntime-gpu
```
2. Change the following dependency in the `custom_nodes/ComfyUI-YoloWorld-EfficientSAM` project [requirements.txt](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/blob/main/requirements.txt)
```
# remove inference-gpu[yolo-world]==0.9.13
inference[yolo-world]==0.9.13
```
3. Then reinstall the dependencies
```
pip install -r requirements.txt
```

**Comment by RebornXD** [comment]
try this: change `from inference.models import YOLOWorld` to `from inference.models.yolo_world import YOLOWorld`

https://github.com/roboflow/inference/issues/389
