### ISSUE TITLE
EfficientSAM， Suddenly an error message appears!

### ISSUE THREAD

**Issue by goodBOY-05** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#71]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: invalid vector subscript

Traceback (most recent call last):
  File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 149, in yoloworld_esam_image
    detections.mask = inference_with_boxes(
  File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\utils\efficient_sam.py", line 59, in inference_with_boxes
    mask = inference_with_box(image, box, model, device)
  File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\utils\efficient_sam.py", line 28, in inference_with_box
    predicted_logits, predicted_iou = model(
  File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: invalid vector subscript

**Comment by goodBOY-05** [comment]
![微信图片_20240710101215](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/assets/169134173/9f77151e-6c0d-4d4b-aa27-902f715eb2a6)

**Comment by alenknight** [comment]
i'm getting this error too.

**Comment by DavidSnow1** [comment]
Same error too.

**Comment by DavidSnow1** [comment]
So. I've been getting errors for a couple of weeks, and I've finally managed to get Yoloworld to work again. The workaround sucks, but seeing as very few issues are actually responded to on here, I suggest you follow my advice if you actually want to get this working. 

When I first got these errors, I realised they were cuda related, so naturally, I switched the Esam loader device to "CPU", but that threw up errors too. After doing a bit of digging, I found this pull request that fixed the issue:

https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/pull/32

This was not merged into this branch, so ltdrdata made his own branch that actually works. 

Enough preamble. This is how you fix this error.

Delete the Yoloworld custom node folder. Yes, you heard me. We are going to reinstall from scratch.
Open a command prompt in your custom nodes folder. 

`git clone https://github.com/ltdrdata/ComfyUI-YoloWorld-EfficientSAM` (This is the fork that works)
`cd custom_nodes/ComfyUI-YoloWorld-EfficientSAM`
`pip install -r requirements.txt`

Now, download these files into your Yoloworld efficient Sam custom node directory: 

https://huggingface.co/camenduru/YoloWorld-EfficientSAM/blob/main/efficient_sam_s_cpu.jit
https://huggingface.co/camenduru/YoloWorld-EfficientSAM/blob/main/efficient_sam_s_gpu.jit

Restart comfy. Load your Yoloworld node like normal. Change the device from GPU to CPU, and it will work. GPU will probably still be busted, but I have no faith that this is going to be patched anytime soon. This way, you actually have something that works. Hope that helped. 

![cpu](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/assets/128657205/5ad9fbe7-c87b-4bae-81d7-cc0c4d27c1bc)

**Comment by alenknight** [comment]
> So. I've been getting errors for a couple of weeks, and I've finally managed to get Yoloworld to work again. The workaround sucks, but seeing as very few issues are actually responded to on here, I suggest you follow my advice if you actually want to get this working.
> 
> When I first got these errors, I realised they were cuda related, so naturally, I switched the Esam loader device to "CPU", but that threw up errors too. After doing a bit of digging, I found this pull request that fixed the issue:
> 
> #32
> 
> This was not merged into this branch, so ltdrdata made his own branch that actually works.
> 
> Enough preamble. This is how you fix this error.
> 
> Delete the Yoloworld custom node folder. Yes, you heard me. We are going to reinstall from scratch. Open a command prompt in your custom nodes folder.
> 
> `git clone https://github.com/ltdrdata/ComfyUI-YoloWorld-EfficientSAM` (This is the fork that works) `cd custom_nodes/ComfyUI-YoloWorld-EfficientSAM` `pip install -r requirements.txt`
> 
> Now, download these files into your Yoloworld efficient Sam custom node directory:
> 
> https://huggingface.co/camenduru/YoloWorld-EfficientSAM/blob/main/efficient_sam_s_cpu.jit https://huggingface.co/camenduru/YoloWorld-EfficientSAM/blob/main/efficient_sam_s_gpu.jit
> 
> Restart comfy. Load your Yoloworld node like normal. Change the device from GPU to CPU, and it will work. GPU will probably still be busted, but I have no faith that this is going to be patched anytime soon. This way, you actually have something that works. Hope that helped.
> 
> ![cpu](https://private-user-images.githubusercontent.com/128657205/347606688-5ad9fbe7-c87b-4bae-81d7-cc0c4d27c1bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NTgwODMsIm5iZiI6MTcyMDY1Nzc4MywicGF0aCI6Ii8xMjg2NTcyMDUvMzQ3NjA2Njg4LTVhZDlmYmU3LWM4N2ItNGJhZS04MWQ3LWNjMGM0ZDI3YzFiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwMDI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzdhZmZiZWM5MWRkZDBiNWE3OGFjZmVjZTY3ZDZhMTZlODVlYjVlMTJjNGFiYzljOGM2ODdmYzE1MGI4MGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uQYtTxyUPCwwMVvj3J0vcJb6mCTTwC9pUD9acX8gLwk)

THAT fixed it... though now my wdtagger v3 broke. lol.  it's cause of the onnxruntime change .... but this did fix the issue.  THANKS!

**Comment by goodBOY-05** [comment]
Reinstall the building model file according to the process, but the error still persists.



Error occurred when executing Yoloworld_ESAM_Zho:

The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
File "code/__torch__/d2go/projects/sam/model/sam.py", line 31, in
_1 = torch.eq(fusion_type0, "hybrid")
if _1:
image_embeddings0 = (self).get_image_embeddings_with_early_fusion(batched_images, batched_points, batched_point_labels, )
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
image_embeddings = image_embeddings0
else:
File "code/__torch__/d2go/projects/sam/model/sam.py", line 135, in get_image_embeddings_with_early_fusion
batched_points: Tensor,
batched_point_labels: Tensor) -> List[Tensor]:
batched_images2 = (self).preprocess(batched_images, )
~~~~~~~~~~~~~~~~ <--- HERE
batch_size, _60, H, W, = torch.size(batched_images2)
max_num_queries = (torch.size(batched_points))[1]
File "code/__torch__/d2go/projects/sam/model/sam.py", line 241, in preprocess
x0 = x
pixel_mean = self.pixel_mean
_94 = torch.sub(x0, pixel_mean)
~~~~~~~~~ <--- HERE
pixel_std = self.pixel_std
return torch.div(_94, pixel_std)

Traceback of TorchScript, original code (most recent call last):
File "/mnt/xarfuse/uid-462794/44f9c4d0-seed-bf15d98d-c01d-4b13-b2d3-09941a262007-ns-4026536022/d2go/projects/sam/model/sam.py", line 642, in
batch_size, _, _, _ = batched_images.shape
if self.fusion_type == "early" or self.fusion_type == "hybrid":
image_embeddings = self.get_image_embeddings_with_early_fusion(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
batched_images, batched_points, batched_point_labels
)
File "/mnt/xarfuse/uid-462794/44f9c4d0-seed-bf15d98d-c01d-4b13-b2d3-09941a262007-ns-4026536022/d2go/projects/sam/model/sam.py", line 608, in get_image_embeddings_with_early_fusion
The last embedding corresponds to the final layer.
"""
batched_images = self.preprocess(batched_images)
~~~~~~~~~~~~~~~ <--- HERE
batch_size, _, H, W = batched_images.shape
max_num_queries = batched_points.shape[1]
File "/mnt/xarfuse/uid-462794/44f9c4d0-seed-bf15d98d-c01d-4b13-b2d3-09941a262007-ns-4026536022/d2go/projects/sam/model/sam.py", line 672, in preprocess
mode="bilinear",
)
return (x - self.pixel_mean) / self.pixel_std
~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!



File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 149, in yoloworld_esam_image
detections.mask = inference_with_boxes(
File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\utils\efficient_sam.py", line 59, in inference_with_boxes
mask = inference_with_box(image, box, model, device)
File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\utils\efficient_sam.py", line 28, in inference_with_box
predicted_logits, predicted_iou = model(
File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\ComfyUI_Mie_V2.0\ComfyUI_Mie_V2.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)

**Comment by mmacheng** [comment]
![image](https://github.com/user-attachments/assets/7ae6511a-2787-40cf-b15e-cb388ea3ed74)
关掉这个选项就会正常

**Comment by alenhrp** [comment]
> ![image](https://private-user-images.githubusercontent.com/88197887/348467785-7ae6511a-2787-40cf-b15e-cb388ea3ed74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzI4NzUsIm5iZiI6MTcyMTAzMjU3NSwicGF0aCI6Ii84ODE5Nzg4Ny8zNDg0Njc3ODUtN2FlNjUxMWEtMjc4Ny00MGNmLWIxNWUtY2IzODhlYTNlZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4MzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOTk1YzVhYzc4M2M5ZTg0NGNkOGFjYmE2OTYzMThlOTcyODYzMTE5NGE2YWVkNDVmMzYyMjJkYzJjZjI5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c9heO3frZp7ErKRiAPp3NFQ04U3CCbavcmxOWFCxM1U) 关掉这个选项就会正常

但是mask还是不能输出，你的可以嘛？

**Comment by codingcn** [comment]
> > ![image](https://private-user-images.githubusercontent.com/88197887/348467785-7ae6511a-2787-40cf-b15e-cb388ea3ed74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzI4NzUsIm5iZiI6MTcyMTAzMjU3NSwicGF0aCI6Ii84ODE5Nzg4Ny8zNDg0Njc3ODUtN2FlNjUxMWEtMjc4Ny00MGNmLWIxNWUtY2IzODhlYTNlZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4MzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOTk1YzVhYzc4M2M5ZTg0NGNkOGFjYmE2OTYzMThlOTcyODYzMTE5NGE2YWVkNDVmMzYyMjJkYzJjZjI5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c9heO3frZp7ErKRiAPp3NFQ04U3CCbavcmxOWFCxM1U) 关掉这个选项就会正常
> 
> 但是mask还是不能输出，你的可以嘛？

![image](https://github.com/user-attachments/assets/852fd949-dcba-4189-8c4f-b8e711a2bbf7)
关了后，一样报错

**Comment by Alex-Ning** [comment]
Try disable [ComfyUI-Easy-Use](https://github.com/yolain/ComfyUI-Easy-Use)

**Comment by el1xz** [comment]
I also faced this problem
I decided to disable all unused nodes. After rebooting Comfy, my workflow worked!

**Comment by alenhrp** [comment]
> > So. I've been getting errors for a couple of weeks, and I've finally managed to get Yoloworld to work again. The workaround sucks, but seeing as very few issues are actually responded to on here, I suggest you follow my advice if you actually want to get this working.
> > When I first got these errors, I realised they were cuda related, so naturally, I switched the Esam loader device to "CPU", but that threw up errors too. After doing a bit of digging, I found this pull request that fixed the issue:
> > #32
> > This was not merged into this branch, so ltdrdata made his own branch that actually works.
> > Enough preamble. This is how you fix this error.
> > Delete the Yoloworld custom node folder. Yes, you heard me. We are going to reinstall from scratch. Open a command prompt in your custom nodes folder.
> > `git clone https://github.com/ltdrdata/ComfyUI-YoloWorld-EfficientSAM` (This is the fork that works) `cd custom_nodes/ComfyUI-YoloWorld-EfficientSAM` `pip install -r requirements.txt`
> > Now, download these files into your Yoloworld efficient Sam custom node directory:
> > https://huggingface.co/camenduru/YoloWorld-EfficientSAM/blob/main/efficient_sam_s_cpu.jit https://huggingface.co/camenduru/YoloWorld-EfficientSAM/blob/main/efficient_sam_s_gpu.jit
> > Restart comfy. Load your Yoloworld node like normal. Change the device from GPU to CPU, and it will work. GPU will probably still be busted, but I have no faith that this is going to be patched anytime soon. This way, you actually have something that works. Hope that helped.
> > ![cpu](https://private-user-images.githubusercontent.com/128657205/347606688-5ad9fbe7-c87b-4bae-81d7-cc0c4d27c1bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NTgwODMsIm5iZiI6MTcyMDY1Nzc4MywicGF0aCI6Ii8xMjg2NTcyMDUvMzQ3NjA2Njg4LTVhZDlmYmU3LWM4N2ItNGJhZS04MWQ3LWNjMGM0ZDI3YzFiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwMDI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzdhZmZiZWM5MWRkZDBiNWE3OGFjZmVjZTY3ZDZhMTZlODVlYjVlMTJjNGFiYzljOGM2ODdmYzE1MGI4MGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uQYtTxyUPCwwMVvj3J0vcJb6mCTTwC9pUD9acX8gLwk)
> 
> THAT fixed it... though now my wdtagger v3 broke. lol. it's cause of the onnxruntime change .... but this did fix the issue. THANKS!

要求inference-gpu[yolo-world]==0.9.13，但是最新版已经0.20.1，如何处理才能继续保证导出正常使用，谢谢
