### ISSUE TITLE
Error occurred when executing Yoloworld_ESAM_Zho:  cannot import name 'packaging' from 'pkg_resources'

### ISSUE THREAD

**Issue by hong2610** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#79]
think you.
![屏幕截图 2024-07-18 141006](https://github.com/user-attachments/assets/5971a648-a591-4fc6-bd12-6d81bb760674)

**Comment by neozbr** [comment]
I've got exactly same error too...

**Comment by huangkun1985** [comment]
`requirements: Ultralytics requirement ['git+https://github.com/ultralytics/CLIP.git'] not found, attempting AutoUpdate...
  Running command git clone --filter=blob:none --quiet https://github.com/ultralytics/CLIP.git 'D:\Temp\pip-req-build-q4n_pb7x'

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
requirements: AutoUpdate success ✅ 35.8s, installed 1 package: ['git+https://github.com/ultralytics/CLIP.git']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

!!! Exception during processing!!! cannot import name 'packaging' from 'pkg_resources' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\nn\tasks.py", line 570, in set_classes
    import clip
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\clip\clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 139, in yoloworld_esam_image
    YOLO_WORLD_MODEL.set_classes(categories)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\inference\models\yolo_world\yolo_world.py", line 133, in set_classes
    self.model.set_classes(text)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\yolo\model.py", line 97, in set_classes
    self.model.set_classes(classes)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\nn\tasks.py", line 573, in set_classes
    import clip
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\clip\clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py)

Prompt executed in 36.68 seconds`

**Comment by huangkun1985** [comment]
> think you. ![屏幕截图 2024-07-18 141006](https://private-user-images.githubusercontent.com/173872919/349833825-5971a648-a591-4fc6-bd12-6d81bb760674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTQ0MzcsIm5iZiI6MTcyMTc1NDEzNywicGF0aCI6Ii8xNzM4NzI5MTkvMzQ5ODMzODI1LTU5NzFhNjQ4LWE1OTEtNGZjNi1iZDEyLTZkODFiYjc2MDY3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxNzAyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGI4MjQ1YTY2ZWY4ZDk5MTc3NjI3ZWRhOTNlYTNhOTQ4MDg4NWUxNzQxOTZlZTZmOTMwMGQwNzYxY2I3MWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.goIbZHfq0kmmGsUo9iIhNNvyFI-Gyn6HtGTAeKE3vvI)

same here.

**Comment by WeiYang1982** [comment]
the same to me
