### ISSUE TITLE
RuntimeError: invalid vector subscript

### ISSUE THREAD

**Issue by samen168** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#93]
RuntimeError: invalid vector subscript

[2024-10-22 15:13] 2024-10-22 15:13:07,066- root:393- ERROR- Traceback (most recent call last):
  File "H:\sd\comfy-torch-2.1.2+cu118\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\comfy-torch-2.1.2+cu118\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\comfy-torch-2.1.2+cu118\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\sd\comfy-torch-2.1.2+cu118\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\comfy-torch-2.1.2+cu118\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 149, in yoloworld_esam_image
    detections.mask = inference_with_boxes(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\comfy-torch-2.1.2+cu118\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\utils\efficient_sam.py", line 59, in inference_with_boxes
    mask = inference_with_box(image, box, model, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\comfy-torch-2.1.2+cu118\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\utils\efficient_sam.py", line 28, in inference_with_box
    predicted_logits, predicted_iou = model(
                                      ^^^^^^
  File "H:\sd\comfy-torch-2.1.2+cu118\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\comfy-torch-2.1.2+cu118\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: invalid vector subscript

**Comment by Preston-L** [comment]
I just got the same error as well after updating comfy
